name: Generate Ansible Inventory

on:
  workflow_dispatch:

jobs:
  generate-inventory:
    runs-on: [ ansible-master ]

    steps:
     

      - name: Create inventory directory
        run: |
          sudo -u al mkdir -p /home/al/ansible/
          sudo chown -R al:al /home/al/ansible

      - name: Generate inventory.yaml
        run: |
          sudo -u al bash -c 'cat > /home/al/ansible/inventory.yaml' << 'EOF'
          ---
          all:
            children:
              webservers:
                hosts:
                  web01:
                    ansible_host: 10.128.0.4
                    ansible_user: al
                    

              databases:
                hosts:
                  db01:
                    ansible_host: 10.204.0.2
                    ansible_user: al
                    db_version: 14
